class ProgramEntry {
  const ProgramEntry(
    this.time,
    this.title,
    this.speaker,
    this.details, {
    this.day = 1,
  });
  final String time, title, speaker, details;
  final int day;
}

class ProgramPage {
  const ProgramPage(this.title, this.entries);
  final String title;
  final List<ProgramEntry> entries;
}

// Source: docs/program/summit-2026-source-2026-09-13.txt.
// Untimed activities use their parent session's start time; see import notes.
const programPages = <ProgramPage>[
  ProgramPage("Day 1", [
    ProgramEntry("08:00 AM", "Registration of Participants", "", "", day: 1),
    ProgramEntry("09:00 AM", "Call to Order", "", "", day: 1),
    ProgramEntry("09:03 AM", "Invocation", "City Choir", "", day: 1),
    ProgramEntry(
      "09:08 AM",
      "Philippine National Anthem",
      "City Choir",
      "",
      day: 1,
    ),
    ProgramEntry("09:13 AM", "General Acknowledgements", "", "", day: 1),
    ProgramEntry(
      "09:18 AM",
      "Welcome & Mayor’s Tourism Vision",
      "Hon. Lucilo R. Bayron, City Mayor, Puerto Princesa",
      "",
      day: 1,
    ),
    ProgramEntry(
      "09:50 AM",
      "Puerto Princesa Tourism Opening Production",
      "Banwa Dance Troupe",
      "",
      day: 1,
    ),
    ProgramEntry(
      "09:55 AM",
      "Tourism Summit Overview & Participant Orientation",
      "Mr. Carlos Libosada Jr., Moderator",
      "",
      day: 1,
    ),
    ProgramEntry(
      "10:07 AM",
      "Plenary Session 1: National and Regional Tourism Overview",
      "Roberto P. Alabado III, Regional Director, DOT MIMAROPA",
      "",
      day: 1,
    ),
    ProgramEntry(
      "10:37 AM",
      "Tokens of Appreciation (Serving of AM Snacks)",
      "Hon. Lucilo R. Bayron, City Mayor\n• Mr. Demetrio Alvior Jr., City Tourism Officer",
      "",
      day: 1,
    ),
    ProgramEntry("10:42 AM", "Morning Tea / Venue Reset", "", "", day: 1),
    ProgramEntry(
      "11:02 AM",
      "Tourism Best Practice Showcase",
      "Mr. Carlos Libosada Jr.",
      "",
      day: 1,
    ),
    ProgramEntry(
      "11:02 AM",
      "Best Practice Sharing – Accommodation",
      "TBA",
      "",
      day: 1,
    ),
    ProgramEntry(
      "11:02 AM",
      "Best Practice Sharing – Tourist Destination",
      "Mr. Roy Rodriguez, Owner, Butterfly Garden",
      "",
      day: 1,
    ),
    ProgramEntry(
      "11:02 AM",
      "Best Practice Sharing – Restaurant",
      "Mr. Eric Yayen, Owner, Ka Inato",
      "",
      day: 1,
    ),
    ProgramEntry(
      "11:02 AM",
      "Best Practice Sharing – Tour Operator",
      "Ms. Senith O. Araez, Owner, Whistler Travel and Tours",
      "",
      day: 1,
    ),
    ProgramEntry(
      "11:02 AM",
      "Moderator-Led Synthesis: What Can We Adapt?",
      "Moderator",
      "",
      day: 1,
    ),
    ProgramEntry(
      "12:02 PM",
      "Tokens of Appreciation",
      "Mr. Demetrio Alvior, City Tourism Officer\n• Mr. Bryan John S. Dizon, President, CTC",
      "",
      day: 1,
    ),
    ProgramEntry("12:12 PM", "Lunch Break", "", "", day: 1),
    ProgramEntry(
      "01:12 PM",
      "Plenary Session 2: The Current State of Tourism in Puerto Princesa – Tourism Performance and Industry Outlook",
      "Host",
      "",
      day: 1,
    ),
    ProgramEntry(
      "01:17 PM",
      "Tourism Performance and Product Development",
      "Mr. Demetrio “Toto” Alvior Jr., City Tourism Officer, Puerto Princesa",
      "",
      day: 1,
    ),
    ProgramEntry(
      "01:52 PM",
      "Private Sector Perspective: Tourism Industry Outlook & Current Challenges",
      "Mr. Bryan John S. Dizon, President, City Tourism Council",
      "",
      day: 1,
    ),
    ProgramEntry(
      "02:22 PM",
      "Tourism AVP: Explore Puerto Princesa Promotional AVP",
      "",
      "",
      day: 1,
    ),
    ProgramEntry(
      "02:32 PM",
      "Plenary Session 3: Emerging Tourism Opportunities",
      "Host",
      "",
      day: 1,
    ),
    ProgramEntry(
      "02:32 PM",
      "Sports Development Tourism",
      "Ms. Leonora C. Escollante, President, Philippine Paddling Federation Inc. (PPF)",
      "",
      day: 1,
    ),
    ProgramEntry(
      "03:07 PM",
      "Plenary Session 4: Destination Marketing and Digital Tourism",
      "Host\nMs. Anna Oraiza Aban, Marketing Manager, Israel Ministry of Tourism, Philippines and Singapore",
      "",
      day: 1,
    ),
    ProgramEntry(
      "03:37 PM",
      "Afternoon Tea / Collection of Questionnaires / Venue Reset",
      "",
      "",
      day: 1,
    ),
    ProgramEntry(
      "03:57 PM",
      "Stakeholders’ Panel: From Insights to Action",
      "Mr. Carlos Libosada Jr., Moderator\n• Mr. Demetrio “Toto” Alvior Jr., City Tourism Officer, Puerto Princesa\n• Mr. Bryan John S. Dizon, President, City Tourism Council\n• Coach Len Escollante, President, Philippine Paddling Federation Inc. (PPF)\n• Ms. Anna Oraiza Aban, Marketing Manager, Israel Ministry of Tourism, Philippines and Singapore",
      "Part I – Moderated Discussion: Current Situation, Challenges, Opportunities & Collaboration\nPart II – Participant Questions: Selected Questions & Panel Responses\nPart III – Priority Question: “Puerto Princesa’s Priorities Moving Forward”",
      day: 1,
    ),
    ProgramEntry("04:57 PM", "Tokens of Appreciation", "", "", day: 1),
    ProgramEntry(
      "05:10 PM",
      "Music Entertainment / Synthesis Preparation",
      "City Choir",
      "",
      day: 1,
    ),
    ProgramEntry(
      "05:22 PM",
      "Day 1 Synthesis: What We Heard & What Needs to Change",
      "Mr. Carlos Libosada Jr., Moderator",
      "",
      day: 1,
    ),
    ProgramEntry(
      "05:42 PM",
      "Day 1 Closing & Preview of Day 2",
      "Host",
      "",
      day: 1,
    ),
    ProgramEntry("05:47 PM", "End of Day 1", "", "", day: 1),
  ]),
  ProgramPage("Day 2", [
    ProgramEntry(
      "08:00 AM",
      "Registration & Participants Arrival",
      "",
      "",
      day: 2,
    ),
    ProgramEntry("09:00 AM", "Call to Order", "", "", day: 2),
    ProgramEntry(
      "09:05 AM",
      "Recap of Day 1 Highlights",
      "Mr. Carlos Libosada Jr., Moderator",
      "",
      day: 2,
    ),
    ProgramEntry(
      "09:10 AM",
      "Opening AVP: Puerto Princesa City Tourism Promotional AVP 2026",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "09:15 AM",
      "Plenary Session 1: Tourism Development Framework",
      "Host",
      "",
      day: 2,
    ),
    ProgramEntry(
      "09:20 AM",
      "Puerto Princesa Tourism Code: Initial Presentation",
      "Atty. Herbert S. Dilig, City Councilor of Puerto Princesa, Committee on Legal Matters",
      "",
      day: 2,
    ),
    ProgramEntry(
      "09:45 AM",
      "10-Year Tourism Master Plan: Initial Presentation",
      "Engr. Jovenee C. Sagun, City Planning and Development Officer, City Planning and Development Office",
      "",
      day: 2,
    ),
    ProgramEntry(
      "10:05 AM",
      "Morning Tea / Networking / Collection of Questionnaires / Venue Reset",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "10:25 AM",
      "Panel Discussion, Q&A & Stakeholder Consultation",
      "Mr. Carlos Libosada Jr., Moderator\n• Atty. Herbert S. Dilig, City Councilor of Puerto Princesa, Committee on Legal Matters\n• Engr. Jovenee C. Sagun, City Planning and Development Coordinator, City Planning and Development Office\n• Mr. Demetrio “Toto” Alvior Jr., City Tourism Officer, Puerto Princesa",
      "Part I – Moderator Questioning: Tourism Code & 10-Year Tourism Master Plan\nPart II – Stakeholder Consultation: Questions, Comments, Concerns & Recommendations\nPart III – Further Consultation: Refinements, Inputs & Coordination",
      day: 2,
    ),
    ProgramEntry("11:25 AM", "Tokens of Appreciation", "", "", day: 2),
    ProgramEntry("11:35 AM", "Lunch Break", "", "", day: 2),
    ProgramEntry(
      "12:35 PM",
      "Plenary Session 2: Tourism Development Support, Connectivity & Investment Opportunities",
      "Host",
      "",
      day: 2,
    ),
    ProgramEntry(
      "12:40 PM",
      "Airport Development and Tourism Connectivity",
      "Mr. Glenn Tripulco, Civil Aviation Authority Manager, Civil Aviation Authority of the Philippines",
      "",
      day: 2,
    ),
    ProgramEntry(
      "01:00 PM",
      "Airline Connectivity and Route Development",
      "Mr. Vincent Daniel Gabuco, Area Manager, Philippine Airlines",
      "",
      day: 2,
    ),
    ProgramEntry(
      "01:20 PM",
      "Puerto Princesa Underground River Development Programs",
      "Atty. Christine Longno, Park Superintendent, Puerto Princesa Underground River (PPUR)",
      "",
      day: 2,
    ),
    ProgramEntry(
      "01:37 PM",
      "Tourism AVP: Puerto Princesa Tourism ID",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "01:47 PM",
      "Tourism Safety, Preparedness & Risk Management",
      "Mr. Earl Timbancaya, City Disaster Risk Reduction and Management Officer, City Disaster Risk Reduction and Management Office (CDRRMO)",
      "",
      day: 2,
    ),
    ProgramEntry(
      "02:02 PM",
      "Flagship Program in Tourism",
      "Arch. Onesto Teves, City Architect, City Architecture Office",
      "",
      day: 2,
    ),
    ProgramEntry(
      "02:22 PM",
      "Networking / Venue Reset / Collection of Questionnaires",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "02:37 PM",
      "Stakeholders’ Dialogue: Building the Future of Tourism in Puerto Princesa",
      "Mr. Caloy Libosada, Moderator",
      "Part I – Moderated Discussion: Connectivity, Development, Sustainability, Safety & Investment\nPart II – Participant Questions & Reactions: Questions, Concerns, Insights & Recommendations\nPart III – Priority Actions & Recommendations: Priorities & Collaboration",
      day: 2,
    ),
    ProgramEntry(
      "02:42 PM",
      "Stakeholders’ Dialogue – Batch 1",
      "• Mr. Glenn Tripulco, Civil Aviation Authority Manager, Civil Aviation Authority of the Philippines\n• Mr. Vincent Daniel Gabuco, Area Manager, Philippine Airlines\n• Atty. Christine Logno, Park Superintendent, Puerto Princesa Underground River (PPUR)",
      "",
      day: 2,
    ),
    ProgramEntry("03:12 PM", "Token of Appreciation | Batch 1", "", "", day: 2),
    ProgramEntry(
      "03:22 PM",
      "Afternoon Tea / Networking / Collection of Questionnaires",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "03:42 PM",
      "Stakeholders’ Dialogue – Batch 2",
      "• Mr. Earl Timbancaya, City Disaster Risk Reduction and Management Officer, City Disaster Risk Reduction and Management Office (CDRRMO)\n• Arch. Onesto Teves, City Architect, City Architecture Office",
      "",
      day: 2,
    ),
    ProgramEntry("04:12 PM", "Token of Appreciation | Batch 2", "", "", day: 2),
    ProgramEntry(
      "04:22 PM",
      "Networking / Synthesis Preparation",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "04:37 PM",
      "Synthesis: Key Insights, Priorities & Next Steps (3 Resolutions)",
      "Mr. Carlos Libosada Jr.",
      "",
      day: 2,
    ),
    ProgramEntry(
      "05:02 PM",
      "Tourism Commitment Wall Signing Ceremony",
      "Mr. Demetrio “Toto” Alvior Jr., City Tourism Officer of Puerto Princesa\n• Mr. Bryan John S. Dizon, President, City Tourism Council",
      "",
      day: 2,
    ),
    ProgramEntry(
      "05:20 PM",
      "Message of Support & Appreciation",
      "Mr. Bryan John S. Dizon, President, City Tourism Council",
      "",
      day: 2,
    ),
    ProgramEntry(
      "05:25 PM",
      "Acknowledgement, Formal Closing & Group Photo",
      "Host",
      "",
      day: 2,
    ),
    ProgramEntry("05:40 PM", "End of Summit", "", "", day: 2),
  ]),
];
