class ProgramEntry {
  const ProgramEntry(
    this.time,
    this.title,
    this.speaker,
    this.details, {
    this.day = 1,
  });
  final String time, title, speaker, details;
  final int day;
}

class ProgramPage {
  const ProgramPage(this.title, this.entries);
  final String title;
  final List<ProgramEntry> entries;
}

// Source: docs/program/summit-2026-source-2026-09-15.txt.
// Untimed activities use their parent session's start time; see import notes.
const programPages = <ProgramPage>[
  ProgramPage("Day 1", [
    ProgramEntry("08:00 AM", "Registration of Participants", "", "", day: 1),
    ProgramEntry("09:00 AM", "Call to Order", "", "", day: 1),
    ProgramEntry("09:03 AM", "Invocation", "City Choir", "", day: 1),
    ProgramEntry(
      "09:08 AM",
      "Philippine National Anthem",
      "City Choir",
      "",
      day: 1,
    ),
    ProgramEntry("09:13 AM", "General Acknowledgements", "", "", day: 1),
    ProgramEntry(
      "09:18 AM",
      "Welcome & Mayor’s Tourism Vision",
      "Hon. Lucilo R. Bayron, City Mayor, Puerto Princesa",
      "",
      day: 1,
    ),
    ProgramEntry(
      "09:50 AM",
      "Puerto Princesa Tourism Opening Production",
      "Banwa Dance Troupe",
      "",
      day: 1,
    ),
    ProgramEntry(
      "09:55 AM",
      "Tourism Summit Overview & Participant Orientation",
      "Carlos M. Libosada Jr., Moderator, Tourism Summit",
      "",
      day: 1,
    ),
    ProgramEntry(
      "10:07 AM",
      "Plenary Session 1: National and Regional Tourism Overview",
      "Roberto P. Alabado III, Regional Director, Department of Tourism, Mimaropa",
      "",
      day: 1,
    ),
    ProgramEntry(
      "10:37 AM",
      "Tokens of Appreciation",
      "Hon. Lucilo R. Bayron, City Mayor, Puerto Princesa\n• Demetrio “Toto” C. Alvior Jr., City Tourism Officer, Puerto Princesa",
      "",
      day: 1,
    ),
    ProgramEntry("10:42 AM", "Morning Tea", "", "", day: 1),
    ProgramEntry(
      "11:02 AM",
      "Tourism Best Practice Showcase",
      "Carlos M. Libosada Jr., Moderator, Tourism Summit",
      "",
      day: 1,
    ),
    ProgramEntry(
      "11:02 AM",
      "Best Practice Sharing – Accommodation",
      "George Michael T. Iñigo, Hotel Manager, Best Western Plus The Ivywall Hotel",
      "",
      day: 1,
    ),
    ProgramEntry(
      "11:02 AM",
      "Best Practice Sharing – Tourist Destination",
      "Roy Rodriguez, Owner, Butterfly Garden",
      "",
      day: 1,
    ),
    ProgramEntry(
      "11:02 AM",
      "Best Practice Sharing – Restaurant",
      "Eric John Yayen, Owner, Ka Inato",
      "",
      day: 1,
    ),
    ProgramEntry(
      "11:02 AM",
      "Best Practice Sharing – Tour Operator",
      "Senith O. Araez, Owner, Whistler Travel and Tours",
      "",
      day: 1,
    ),
    ProgramEntry(
      "11:02 AM",
      "Moderator-Led Synthesis: What Can We Adapt?",
      "Moderator",
      "",
      day: 1,
    ),
    ProgramEntry(
      "12:02 PM",
      "Tokens of Appreciation",
      "Demetrio “Toto” C. Alvior Jr., City Tourism Officer, Puerto Princesa\n• Bryan John S. Dizon, President, City Tourism Council\n• Carlos M. Libosada Jr., Moderator, Tourism Summit",
      "",
      day: 1,
    ),
    ProgramEntry("12:12 PM", "Lunch Break", "", "", day: 1),
    ProgramEntry(
      "01:12 PM",
      "Plenary Session 2: The Current State of Tourism in Puerto Princesa – Tourism Performance and Industry Outlook",
      "",
      "",
      day: 1,
    ),
    ProgramEntry(
      "01:17 PM",
      "Tourism Performance and Product Development",
      "Demetrio “Toto” C. Alvior Jr., City Tourism Officer, Puerto Princesa",
      "",
      day: 1,
    ),
    ProgramEntry(
      "01:52 PM",
      "Private Sector Perspective: Tourism Industry Outlook & Current Challenges",
      "Bryan John S. Dizon, President, City Tourism Council",
      "",
      day: 1,
    ),
    ProgramEntry(
      "02:22 PM",
      "Tourism Audio-Visual Presentation: Explore Puerto Princesa Promotional Audio-Visual Presentation",
      "",
      "",
      day: 1,
    ),
    ProgramEntry(
      "02:32 PM",
      "Plenary Session 3: Emerging Tourism Opportunities",
      "",
      "",
      day: 1,
    ),
    ProgramEntry(
      "02:32 PM",
      "Sports Development Tourism",
      "Leonora C. Escollante, President, Philippine Paddling Federation Incorporated",
      "",
      day: 1,
    ),
    ProgramEntry(
      "03:07 PM",
      "Plenary Session 4: Destination Marketing and Digital Tourism",
      "Anna Oraiza T. Aban, Marketing Manager, Israel Ministry of Tourism, Philippines and Singapore",
      "",
      day: 1,
    ),
    ProgramEntry(
      "03:37 PM",
      "Afternoon Tea / Collection of Questionnaires",
      "",
      "",
      day: 1,
    ),
    ProgramEntry(
      "03:57 PM",
      "Stakeholders’ Panel: From Insights to Action",
      "Carlos M. Libosada Jr., Moderator, Tourism Summit\n• Demetrio “Toto” C. Alvior Jr., City Tourism Officer, Puerto Princesa\n• Bryan John S. Dizon, President, City Tourism Council\n• Leonora C. Escollante, President, Philippine Paddling Federation Incorporated\n• Anna Oraiza T. Aban, Marketing Manager, Israel Ministry of Tourism, Philippines and Singapore",
      "Part I – Moderated Discussion: Current Situation, Challenges, Opportunities & Collaboration\nPart II – Participant Questions: Selected Questions & Panel Responses\nPart III – Priority Question: “Puerto Princesa’s Priorities Moving Forward”",
      day: 1,
    ),
    ProgramEntry(
      "04:57 PM",
      "Tokens of Appreciation",
      "Roberto P. Alabado III, Regional Director, Department of Tourism, Mimaropa\n• Carlos M. Libosada Jr., Moderator, Tourism Summit",
      "",
      day: 1,
    ),
    ProgramEntry(
      "05:10 PM",
      "Music Entertainment / Synthesis Preparation",
      "City Choir",
      "",
      day: 1,
    ),
    ProgramEntry(
      "05:22 PM",
      "Day 1 Synthesis: What We Heard & What Needs to Change",
      "Carlos M. Libosada Jr., Moderator, Tourism Summit",
      "",
      day: 1,
    ),
    ProgramEntry(
      "05:42 PM",
      "Day 1 Closing & Preview of Day 2",
      "",
      "",
      day: 1,
    ),
    ProgramEntry("05:47 PM", "End of Day 1", "", "", day: 1),
  ]),
  ProgramPage("Day 2", [
    ProgramEntry(
      "08:00 AM",
      "Registration & Participants Arrival",
      "",
      "",
      day: 2,
    ),
    ProgramEntry("09:00 AM", "Call to Order", "", "", day: 2),
    ProgramEntry(
      "09:05 AM",
      "Recap of Day 1 Highlights",
      "Carlos M. Libosada Jr., Moderator, Tourism Summit",
      "",
      day: 2,
    ),
    ProgramEntry(
      "09:10 AM",
      "Opening Audio-Visual Presentation: Puerto Princesa City Tourism Promotional Audio-Visual Presentation 2026",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "09:15 AM",
      "Plenary Session 1: Tourism Development Framework",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "09:20 AM",
      "Puerto Princesa Tourism Code",
      "Atty. Herbert S. Dilig, City Councilor, Puerto Princesa Council – Committee on Legal Matters",
      "",
      day: 2,
    ),
    ProgramEntry(
      "09:45 AM",
      "10-Year Tourism Master Plan",
      "Engr. Jovenee C. Sagun, City Planning and Development Officer, Puerto Princesa",
      "",
      day: 2,
    ),
    ProgramEntry(
      "10:05 AM",
      "Morning Tea / Networking / Collection of Questionnaires",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "10:25 AM",
      "Panel Discussion, Question and Answer & Stakeholder Consultation",
      "Carlos M. Libosada Jr., Moderator, Tourism Summit\n• Atty. Herbert S. Dilig, City Councilor, Puerto Princesa Council – Committee on Legal Matters\n• Engr. Jovenee C. Sagun, City Planning and Development Officer, Puerto Princesa\n• Demetrio “Toto” C. Alvior Jr., City Tourism Officer, Puerto Princesa",
      "Part I – Moderator Questioning: Tourism Code & 10-Year Tourism Master Plan\nPart II – Stakeholder Consultation: Questions, Comments, Concerns & Recommendations\nPart III – Further Consultation: Refinements, Inputs & Coordination",
      day: 2,
    ),
    ProgramEntry(
      "11:25 AM",
      "Tokens of Appreciation",
      "Demetrio “Toto” C. Alvior Jr., City Tourism Officer, Puerto Princesa\n• Bryan John S. Dizon, President, City Tourism Council\n• Carlos M. Libosada Jr., Moderator, Tourism Summit",
      "",
      day: 2,
    ),
    ProgramEntry("11:35 AM", "Lunch Break", "", "", day: 2),
    ProgramEntry(
      "12:35 PM",
      "Plenary Session 2: Tourism Development Support, Connectivity & Investment Opportunities",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "12:40 PM",
      "Airport Development and Tourism Connectivity",
      "Glenn Tripulco, Manager, Civil Aviation Authority of the Philippines",
      "",
      day: 2,
    ),
    ProgramEntry(
      "01:00 PM",
      "Airline Connectivity and Route Development",
      "Daniel Vincent Gabuco, Area Manager, Philippine Airlines",
      "",
      day: 2,
    ),
    ProgramEntry(
      "01:20 PM",
      "Puerto Princesa Underground River Development Programs",
      "Atty. Christine N. Longno, Park Superintendent, Puerto Princesa Underground River",
      "",
      day: 2,
    ),
    ProgramEntry(
      "01:37 PM",
      "Tourism Audio-Visual Presentation: Puerto Princesa Tourism ID",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "01:47 PM",
      "Tourism Safety, Preparedness & Risk Management",
      "Earl H. Timbancaya, City Disaster Risk Reduction and Management Officer, Puerto Princesa",
      "",
      day: 2,
    ),
    ProgramEntry(
      "02:07 PM",
      "Flagship Program in Tourism",
      "Arch. Onesto R. Teves, City Architect, Puerto Princesa",
      "",
      day: 2,
    ),
    ProgramEntry(
      "02:22 PM",
      "Networking / Collection of Questionnaires",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "02:37 PM",
      "Stakeholders’ Dialogue: Building the Future of Tourism in Puerto Princesa",
      "Carlos M. Libosada Jr., Moderator, Tourism Summit",
      "Part I – Moderated Discussion: Connectivity, Development, Sustainability, Safety & Investment\nPart II – Participant Questions & Reactions: Questions, Concerns, Insights & Recommendations\nPart III – Priority Actions & Recommendations: Priorities & Collaboration",
      day: 2,
    ),
    ProgramEntry(
      "02:42 PM",
      "Stakeholders’ Dialogue – Batch 1",
      "• Glenn Tripulco, Manager, Civil Aviation Authority of the Philippines\n• Daniel Vincent Gabuco, Area Manager, Philippine Airlines\n• Atty. Christine N. Longno, Park Superintendent, Puerto Princesa Underground River",
      "",
      day: 2,
    ),
    ProgramEntry(
      "03:12 PM",
      "Afternoon Tea / Networking / Collection of Questionnaires",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "03:27 PM",
      "Stakeholders’ Dialogue – Batch 2",
      "• Earl H. Timbancaya, City Disaster Risk Reduction and Management Officer, Puerto Princesa\n• Arch. Onesto R. Teves, City Architect, Puerto Princesa",
      "",
      day: 2,
    ),
    ProgramEntry(
      "03:57 PM",
      "Token of Appreciation of Batch 1 & 2 Panelists",
      "Demetrio “Toto” C. Alvior Jr., City Tourism Officer, Puerto Princesa\n• Bryan John S. Dizon, President, City Tourism Council\n• Carlos M. Libosada Jr., Moderator, Tourism Summit",
      "",
      day: 2,
    ),
    ProgramEntry(
      "04:12 PM",
      "Networking / Synthesis Preparation",
      "",
      "",
      day: 2,
    ),
    ProgramEntry(
      "04:23 PM",
      "Synthesis: Key Insights, Priorities & Next Steps (3 Core Resolutions)",
      "Carlos M. Libosada Jr., Moderator, Tourism Summit",
      "",
      day: 2,
    ),
    ProgramEntry(
      "04:44 PM",
      "Token of Appreciation to the Moderator",
      "Demetrio “Toto” C. Alvior Jr., City Tourism Officer, Puerto Princesa\n• Bryan John S. Dizon, President, City Tourism Council",
      "Recipient: Carlos M. Libosada Jr.",
      day: 2,
    ),
    ProgramEntry(
      "04:50 PM",
      "Tourism Commitment Wall Signing Ceremony",
      "Demetrio “Toto” C. Alvior Jr., City Tourism Officer, Puerto Princesa\n• Bryan John S. Dizon, President, City Tourism Council",
      "",
      day: 2,
    ),
    ProgramEntry(
      "05:10 PM",
      "Message of Support & Appreciation",
      "Bryan John S. Dizon, President, City Tourism Council",
      "",
      day: 2,
    ),
    ProgramEntry(
      "05:15 PM",
      "Acknowledgement, Formal Closing & Group Photo",
      "",
      "",
      day: 2,
    ),
    ProgramEntry("05:30 PM", "End of Summit", "", "", day: 2),
  ]),
];

// Canonical displayed names from the speaker title slides.
const programSpeakerNames = <String>[
  "Hon. Lucilo R. Bayron",
  "Carlos M. Libosada Jr.",
  "Roberto P. Alabado III",
  "George Michael T. Iñigo",
  "Roy Rodriguez",
  "Eric John Yayen",
  "Senith O. Araez",
  "Demetrio “Toto” C. Alvior Jr.",
  "Bryan John S. Dizon",
  "Leonora C. Escollante",
  "Anna Oraiza T. Aban",
  "Atty. Herbert S. Dilig",
  "Engr. Jovenee C. Sagun",
  "Glenn Tripulco",
  "Daniel Vincent Gabuco",
  "Atty. Christine N. Longno",
  "Earl H. Timbancaya",
  "Arch. Onesto R. Teves",
];
